[build-system]
requires = [
    "setuptools >= 59.6.0",
    "setuptools_scm >= 6.4.2, <7",
]
build-backend = "setuptools.build_meta"

[tool.black]
target-version = ['py310', 'py311']
skip-string-normalization = true
