[build-system]
requires = [
    "setuptools >= 67.6.1",
    "setuptools_scm >= 7.1.0",
]
build-backend = "setuptools.build_meta"

[tool.black]
target-version = ['py310', 'py311']
skip-string-normalization = true
